apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-platform
  namespace: devops-platform
spec:
  ingressClassName: nginx
  rules:
    - host: devops-platform.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-platform
                port:
                  number: 80
